apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbctest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbctest
    app.kubernetes.io/part-of: fbc-e2e-test
  name: fbctest
  namespace: dev-release-team-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fbctest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fbctest
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:3f9654da995a90a56d8bbe04e3927333e8a1d0798045f7366b558dce4b09ff21
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 50051
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 50051
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
