apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbctest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbctest
    app.kubernetes.io/part-of: fbc-e2e-test
  name: fbctest
  namespace: dev-release-team-tenant
spec:
  port:
    targetPort: 50051
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fbctest
    weight: 100
status: {}
