apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 413-fbc-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 413-fbc-test
    app.kubernetes.io/part-of: fbc-e2e-test
  name: 413-fbc-test
  namespace: dev-release-team-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: 413-fbc-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: 413-fbc-test
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:5e2b2606689556c7e21bc02afb1ca779d825890857dbee616453f5a8d25875b6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 50051
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 50051
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
